//
// Created by Aleksandr Dergachev on 23.05.2020.
//

#ifndef UTILLS__CMD_CODES_H_
#define UTILLS__CMD_CODES_H_

enum CmdCode { UPLOAD, DOWNLOAD, DELETE_FILE, DELETE_USER, LIST, REGISTER, LOGIN };

enum DbErrorCodes{
    DB_CONNECTION_ERROR,
    DB_APPEAL_ERROR,
    DB_REGISTRATION_ERROR,
    DB_ADDING_FILE_RECORD,
    DB_DELETING_USER_ERROR,
    DB_DELETING_FILE_ERROR,
    DB_DELETING_ALL_FILES_ERROR
};

#endif //UTILLS__CMD_CODES_H_
