dist:     trusty
sudo:     required

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

install:
    - if [ $TRAVIS_OS_NAME = linux ]; then source travis/install-linux.sh; fi

script:
    - cd network
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - if [ $TRAVIS_OS_NAME = osx ]; then ctest --verbose --output-on-failure; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then cppcheck --error-exitcode=1 --inconclusive --enable=all --language=c++ ../src ../headers; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all tests/test_network; fi 

    - cd db_app
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - if [ $TRAVIS_OS_NAME = linux ]; then cppcheck --error-exitcode=1 --inconclusive --enable=all --language=c++ ../src ../inc; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all test/db_app_test; fi

    - cd server
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - if [ $TRAVIS_OS_NAME = osx ]; then ctest --verbose --output-on-failure; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then cppcheck --error-exitcode=1 --inconclusive --enable=all --language=c++ ../source ../include; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all tests/test_server; fi 
    
    - cd client_console_app
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
    - if [ $TRAVIS_OS_NAME = osx ]; then ctest --verbose --output-on-failure; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then cppcheck --error-exitcode=1 --inconclusive --enable=all --language=c++ ../src ../inc; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all tests/client_console_app_test; fi 